### ISSUE TITLE
CIGAR mapping off reference

### ISSUE THREAD

**Issue by SaraBakic** [raja-appuswamy/accel-align-release#25]
@SKosier and I are using accel-align in the process of mapping reads from a bisulfite-treated sample to the reference. When we try to deduplicate mappings obtained with accel-align using Picard, we get the following error:

```
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR::CIGAR_MAPS_OFF_REFERENCE:Read name ST-E00127:1123:HG33NCCX2:1:2103:28554:31863, Read CIGAR M operator maps off end of reference
        at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:458)
        at htsjdk.samtools.BAMRecord.getCigar(BAMRecord.java:284)
        at htsjdk.samtools.SAMRecord.isValid(SAMRecord.java:2234)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:862)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:848)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:816)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:591)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:570)
        at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:523)
        at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:258)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

When we check the specified read in .SAM file, we find these mappings:
```
ST-E00127:1123:HG33NCCX2:1:2103:28554:31863     99      NC_000913.3     4641503 60      151M    =       4641563 211    TTGGTAGTGGTAGATGATATAAAATTGGTCGATTGGTTATAATAACGTTTGGGGTTTTTAGAGTAACGAGATACGGTAATGTTGTATCGTTTGTTGTATGATATTGAAAAAAATATTATTAAATAAAAAACGTTTTAGTAAGTATTTTTTA      A-AFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJFJJJJJJJJJJJFJJJFJJFJFAFFFAFJJJJJJJJFJJJJFJJJJJJJJJFJJJJJJJJJJJJJJJFJJJJJJJJJJFFFJJJJJJJJJJJJJJJA     NM:i:0  AS:i:302
ST-E00127:1123:HG33NCCX2:1:2103:28554:31863     147     NC_000913.3     4641563 60      32M119S =       4641503 -211   GAGTAACGAGATACGGTAATGTTGTATCGTTTGTTGTATGATATTGAAAAAAATATTATTAAATAAAAAACGTTTTAGTAAGTATTTTTTAGTTTTTTATTTTGATTGTAACGGGTAATATGTTTTTGTGTGGATTAAAAAAAGAGTGTTT      JJJJJJJJJJJJFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA     NM:i:17 AS:i:-106
```

Also, according to the header:
```
@HD     VN:1.3  SO:coordinate
@SQ     SN:NC_000913.3  LN:4641652
@PG     ID:AccAlign     PN:AccAlign     VN:0.0
```
the reference length is 4641652 which means that the mapping starting at the position 4641503 with CIGAR string 151M does indeed exceed the reference length.
We are wondering what might cause such behavior and is it solvable.

Best regards,
Sanja and Sara

**Comment by yanlolo** [comment]
Dear @SaraBakic and @SKosier ,

Thank you very much for using our aligner and your feedback. We are very intested in the problem you reported. 

The reference length is 4641652 ; the mapping starting at the position 4641503 with CIGAR string 151M. This mapping (4641503+151 = 4641654) indeed exceeds the ref length 4641652. Would you possible to share your reference file such that we could reproduce the error and have a deeper look on our side? You could contact me through yan@eurecom.fr if convenient. Thank you very much.

Best regards,
Yiqing
